---
title: "Fall24-25SwingDecision"
output: html_document
date: "2024-10-31"
---

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(knitr)
```

```{r}
sept_24 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//9-24-24 Live Scrimmage Data.xlsx")
sept_24 <- sept_24[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

sept_25 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//9-25-24 Live Scrimmage Data.xlsx")
sept_25 <- sept_25[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

sept_28 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//9-28-24 Live Scrimmage Data.xlsx")
sept_28 <- sept_28[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 


oct_1 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-1-24 Live Scrimmage Data.xlsx")
oct_1 <- oct_1[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_2 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-2-24 Live Scrimmage Data.xlsx")
oct_2 <- oct_2[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_5 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-5-24 Live Scrimmage Data.xlsx")
oct_5 <- oct_5[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_7 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-7-24 Scout Day.xlsx")
oct_7 <- oct_7[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_9 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-9-24 Live Scrimmage Data.xlsx")
oct_9 <- oct_9[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 


oct_12 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-12-24 Cincy Scrimmage.xlsx")
oct_12 <- oct_12[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide", "PitchLocationConfidence")] 
oct_12 <- oct_12 %>% 
  rename(yt_ZoneAccuracy = PitchLocationConfidence)

oct_16 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-16-24 Live Scrimmage Data.xlsx")
oct_16 <- oct_16[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_18 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-18-24 Mercyhurst Scrimmage Data.xlsx")
oct_18 <- oct_18[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_22 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-22-24 BlueGold1 Scrimmage Data.xlsx")
oct_22 <- oct_22[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_24 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-24-24 BlueGold2 Scrimmage Data.xlsx")
oct_24 <- oct_24[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

oct_26 <- read_excel("C://Users//mason//OneDrive//Pitt Baseball Data//CollectedBaseballData//FALL24-25DATA//10-26-24 BlueGold3 Scrimmage Data.xlsx")
oct_26 <- oct_26[, c("Batter", "BatterTeam", "Balls", "Strikes", "PitchCall", "PlateLocHeight", "PlateLocSide",
                           "yt_ZoneAccuracy")] 

fall_data <- rbind(sept_24, sept_25, sept_28, oct_1, oct_2, oct_5, oct_7, oct_9, oct_12, oct_16, oct_18, oct_22, oct_24, oct_26)
nrow(fall_data)
unique(fall_data$yt_ZoneAccuracy)

fall_data <- fall_data %>% 
  filter(yt_ZoneAccuracy %in% c("High", "high"))
nrow(fall_data)

unique(fall_data$BatterTeam)

fall_data <- fall_data %>% 
  filter(BatterTeam %in% c("Pitt fall 24", "PIT_PAN"))
```

```{r}
# Combining balls and strikes into one "Count" column 
fall_data$Count <- paste(fall_data$Balls, fall_data$Strikes, sep = "-")

# can remove these rows 
fall_data <- fall_data %>%
  select(-yt_ZoneAccuracy, -Balls, -Strikes, -BatterTeam)

# Only need each hitters name, the result of the play, and the location of the pitch.
fall_data

fall_data <- fall_data %>%
  filter(Count == "3-2")

fall_data <- fall_data %>%
  select(-Count)

fall_data
```

```{r}
# Next, need to establish the zone and damage zone, and then will create a new column with a certain label for each result

# The strike zone boundaries 
left_border <- 0.708333
right_border <- -0.708333
lower_border <- 1.5
upper_border <- 3 + (2.5/12)

# Damage zone for 0-0 count (30% reduction of the strike zone)
sides_reduction_value <- (left_border - right_border) * .5 / 2

#damage_left <- left_border - sides_reduction_value
#damage_right <- right_border + sides_reduction_value
damage_left <- left_border
damage_right <- right_border

current_range <- upper_border - lower_border
reduction_amount <- current_range * .5
#damage_upper <- upper_border - (reduction_amount / 2)
#damage_lower <- lower_border + (reduction_amount / 2)
damage_lower <- lower_border
damage_upper <- upper_border

# need radius of baseball to add/subtract to PlateLocSide/Height so pitches that touch the zone are strikes
baseball_diameter_ft <- .241667 
baseball_radius_ft <- baseball_diameter_ft/2 
baseball_radius_ft 


fall_data <- na.omit(fall_data)
fall_data <- fall_data %>%
  mutate(PitchCall = ifelse(PitchCall == "FoulBallNotFieldable", "Foul", PitchCall))
fall_data <- fall_data %>%
  mutate(PitchCall = ifelse(PitchCall == "FoulBallFieldable", "Foul", PitchCall))

fall_data <- fall_data %>%
  mutate(Batter = ifelse(Batter == "Anthony Lasala", "Anthony LaSala", Batter))
fall_data <- fall_data %>%
  mutate(Batter = ifelse(Batter == "Aj Nessler", "AJ Nessler", Batter))
unique(fall_data$Batter)
unique(fall_data$PitchCall)
```

```{r}
# Now, creating labels for each pitch, as the following:
# 1 - Batter swung at pitch in the damage zone 
# 2 - Batter swung at pitch in the strike zone, but not the damage zone 
# 3 - Batter swung at pitch outside of the strike zone 
# 4 - Batter took a pitch in the damage zone 
# 5 - All other takes 

# We know the batter swung if PitchCall = StrikeSwinging, Foul, FoulTip, InPlay 
# We know the batter didn't swing if PitchCall = BallCalled, StrikeCalled, HitByPitch

fall_data <- fall_data %>%
  mutate(
    Labels = ifelse(
      PitchCall %in% c("StrikeSwinging", "Foul", "FoulTip", "InPlay") &
      PlateLocSide <= (damage_left + baseball_radius_ft) & PlateLocSide >= (damage_right - baseball_radius_ft) &
      PlateLocHeight >= (damage_lower - baseball_radius_ft) & PlateLocHeight <= (damage_upper + baseball_radius_ft),
      1,
      NA
    )
  ) %>%
  mutate(
    Labels = ifelse(
      is.na(Labels) &
      PitchCall %in% c("StrikeSwinging", "Foul", "FoulTip", "InPlay") & 
      PlateLocSide <= (left_border + baseball_radius_ft) & PlateLocSide >= (right_border - baseball_radius_ft) &
      PlateLocHeight >= (lower_border - baseball_radius_ft) & PlateLocHeight <= (upper_border + baseball_radius_ft),
      2,
      Labels
    )
  ) %>%
  mutate(
    Labels = ifelse(
      is.na(Labels) &
      PitchCall %in% c("StrikeSwinging", "Foul", "FoulTip", "InPlay"),
      3,
      Labels
    )
  ) %>%
  mutate(
    Labels = ifelse(
      is.na(Labels) &
      PitchCall %in% c("BallCalled", "StrikeCalled", "HitByPitch") &
      PlateLocSide <= (damage_left + baseball_radius_ft) & PlateLocSide >= (damage_right - baseball_radius_ft) &
      PlateLocHeight >= (damage_lower - baseball_radius_ft) & PlateLocHeight <= (damage_upper + baseball_radius_ft),
      4,
      Labels
    )
  ) %>% 
  mutate(
    Labels = ifelse(
      is.na(Labels) &
      PitchCall %in% c("BallCalled", "StrikeCalled", "HitByPitch"),
      5,
      Labels
    )
  )

options(dplyr.print_max = nrow(fall_data))
#fall_data
```

```{r}
# Now, going to calculate the distance each pitch is from the center of the zone 
center_x <- 0 
center_y <- (upper_border + lower_border) / 2 

fall_data <- fall_data %>%
  mutate(DistanceToCenter = sqrt((PlateLocSide - center_x)^2 + (PlateLocHeight - center_y)^2))

#fall_data

# calculate the minimum and maximum distances for each label
min_distances <- fall_data %>%
  group_by(Labels) %>%
  summarize(min_distance = min(DistanceToCenter),
            max_distance = max(DistanceToCenter))

# normalize the distances for each label like:
# 1 - Closest values are 3, furthest yield 1 
# 2 - Closest yield 1, furthest 0 
# 3 - Closest 0, furthest -3 ??? <- may change 
# 4 - Closest 01, furthest 0 
# 5 - All 0's here 

fall_data <- fall_data %>%
  left_join(min_distances, by = "Labels") %>%
  mutate(
    Score = case_when(
      Labels == 1 ~ 3 - (3 - 1) * (DistanceToCenter - min_distance) / (max_distance - min_distance),
      Labels == 2 ~ 1 - (1 - 0) * (DistanceToCenter - min_distance) / (max_distance - min_distance),
      Labels == 3 ~ 0 - (0 - (-3)) * (DistanceToCenter - min_distance) / (max_distance - min_distance),
      Labels == 4 ~ -1 - (-1 - 0) * (DistanceToCenter - min_distance) / (max_distance - min_distance),
      Labels == 5 ~ 0
    )
  )

fall_data$Score
```

```{r}
# Check if 'PitchCall' is "FoulTip"
is_foul_tip <- fall_data$PitchCall == "FoulTip"

# Update 'PitchCall' to "Foul" for rows with "FoulTip"
fall_data$PitchCall[is_foul_tip] <- "Foul"


# If ball is in strike zone (PlateLocSide/PlateLocHeight), and PitchCall == StrikeCalled, StrikeSwinging, change PitchCall to "InZoneStrike"

# Define a condition for balls in the strike zone
in_strike_zone <- (fall_data$PlateLocSide <= (left_border + baseball_radius_ft)) & 
                  (fall_data$PlateLocSide >= (right_border - baseball_radius_ft)) &
                  (fall_data$PlateLocHeight <= (upper_border + baseball_radius_ft)) & 
                  (fall_data$PlateLocHeight >= (lower_border - baseball_radius_ft))

# Check if 'PitchCall' is "StrikeCalled"
is_strike_called <- fall_data$PitchCall == "StrikeCalled"

# Update 'PitchCall' based on conditions
fall_data$PitchCall[in_strike_zone & is_strike_called] <- "InZoneStrikeCalled"


# Now, need to create the plot for each hitter 
all_possible_numbers <- factor(0:7)
legend_labels <-
  c(
    'Other/Unknown Result (0)',
    'BallCalled (1)',
    'StrikeCalled (2)',
    'Foul (3)',
    'InPlay (4)',
    'HitByPitch (5)',
    'StrikeSwinging (6)',
    'InZoneStrikeCalled (7)'
  )

fall_data$number <-
  ifelse(fall_data$PitchCall == 'BallCalled',1,
    ifelse(fall_data$PitchCall == 'StrikeCalled',2,
      ifelse(fall_data$PitchCall == 'Foul',3,
        ifelse(fall_data$PitchCall == 'InPlay',4,
          ifelse(fall_data$PitchCall == 'HitByPitch',5,
            ifelse(fall_data$PitchCall == 'StrikeSwinging',6,
                ifelse(fall_data$PitchCall == 'InZoneStrikeCalled', 7, 0))
              )
            )
          )
        )
      )
    
fall_data$number <- factor(fall_data$number)
```



```{r}
baseball_diameter_cm <- 7.2 
fall_data$Score <- round(fall_data$Score, 2)


unique_batters <- unique(fall_data$Batter)

output_folder <- "falldata_3_2_count"
dir.create(output_folder, showWarnings = FALSE)
```


```{r}
for (batter in unique_batters) {
  sub_data <- subset(fall_data, Batter == batter)
  
  p <- ggplot(sub_data, aes(x = PlateLocSide, y = PlateLocHeight)) +
    geom_point(size = baseball_diameter_cm, aes(color = number)) +
    geom_text(aes(label = number), vjust = 0, size = 2) +
    geom_text(aes(label = Score), vjust = 1, size = 5) +
    geom_rect(
      aes(
        xmin = right_border,
        xmax = left_border,
        ymin = lower_border,
        ymax = upper_border
      ),
      color = 'black',
      fill = NA
    ) +
    geom_rect(
      aes(
        xmin = damage_right,
        xmax = damage_left,
        ymin = damage_lower,
        ymax = damage_upper
      ),
      color = 'red',
      fill = NA
    ) +
    coord_cartesian(xlim = c(2.5, -2.5), ylim = c(0, 4.5)) +
    scale_color_manual(
      values = c(
        "0" = "black",
        "1" = "green",
        "2" = "red",
        "3" = "steelblue",
        "4" = "steelblue",
        "5" = "green",
        "6" = "yellow",
        "7" = 'purple'
      ),
      breaks = all_possible_numbers,
      labels = legend_labels
    ) +
    labs(
      title = paste(batter, "With 3-2 Count"),
      x = "Distance from Center",
      y = "Height from Ground",
      color = "Number"
    )
  
  # Define the filename for each plot
  plot_filename <- file.path(output_folder, paste(batter, "3-2plot.png"))
  # Save the plot to the specified filename
  ggsave(filename = plot_filename, plot = p, width = 8, height = 6, dpi = 300)
  
  print(p)
}
```

```{r}
summed_scores <- fall_data %>%
  group_by(Batter) %>%
  summarize(
    Pitches = n(),
    Total_Score = sum(Score),
    Average_Score = mean(Score)
  )

sorted_summed_scores <- summed_scores %>%
  arrange(desc(Average_Score))

sorted_summed_scores

```
